### PR TITLE
v4.8.1.3 Methane module, multiple fertilizers, compile warning reduction

### PR DESCRIPTION
**Pull request by chporter**
Methane module:
- input SAEA in soil analysis section of FileX, default value of 26.5 mol Ceq/m3 (previously hard-wired).
- allow fertilizers to affect buffer for methane production (so far only ammonium sulfate and potassium sulfate are handled)

Other changes:
- handle multiple fertilizers in one day correctly (previously bug might accumulate N amounts)
- Align units in GHG.OUT with Data.CDE
- Loads of EXTERNAL statements 
- Remove unused variables
- Reduce long lines

I have fully tested these changes. The methane module change to allow fertilizers to affect methane production has some minor effects on CO2 and CH4 emissions for some rice experiments. No other experiments were affected by the changes.

NOTE: this does not include the Soil Temperature change from Bruce Kimball and Kelly Thorp. Please test that separately!

### CODE REVIEW

**Comment by chporter** [comment]
OK - just seeing that there are conflicts with Thiago's file changes. I didn't see any conflicts on my machine. Will have to investigate.

**Comment by chporter** [comment]
The compile warnings have been fully eliminated with this version, with today's update. I tested the following:
- All standard DSSAT experiments and treatments, summary.out
- tested alternate crop models: CASUPRO, Ceres-Teff, CSCAS, CSCRP, IXIM, NWheat, SAMUCA
- for randomly selected experiments / treatments, tested CSV outputs, detailed outputs, potential production, and sulieman ES

All the above tested without issues.

**Comment by chporter** [comment]
Thiago got a compile error because of the SYSTEM functions listed in the EXTERNAL statements. I removed them in this version.
We now get two compiler warning messages :-(

**Comment by chporter** [comment]
@thiagoferreira53 @fabiooliveira72 @kthorp 
Please test to see if you still get compile warnings with this version.
Thanks!

**Comment by fabiooliveira72** [comment]
> @thiagoferreira53 @fabiooliveira72 @kthorp
> Please test to see if you still get compile warnings with this version.
> Thanks!

Hi Cheryl!

Yes, I can check that too. I think this is some cyclical dependency based on the system. I will report back if I find anything.

**Comment by fabiooliveira72** [comment]
Hi @chporter!

I tested your branch compared with the latest DSSAT/develop and the new commit that you removed the system from external.

Please see below the tests and comments:
- [x] Compiling process (Intel & Gfortran)
- [x] Batch Run for all crops (Intel & Gfortran)
             - No differences found except for:
                      - RICER048, experiment DTSP8502.RIX, treatment 2 to 6:
                                   - The differences was only for CH2EM and CH4EM (Already mentioned in your previous comment)

Cheryl, this pull request is ready to merge!

Thank you. Let me know if you need anything else.

Fabio Oliveira

**Comment by chporter** [comment]
I added one more commit - tested out OK.

**Pull request merged**
