### PR TITLE
Water table

### PR DESCRIPTION
**Pull request by chporter**
Water table model reads user-input water table depths from irrigation section (IR007 records, depth in cm).
- the water table is managed at the user-specified depth until another depth is entered. There is no interpolation between entries.
- In order to conserve mass of water, lateral inflows and outflows are calculated because a change in water table implies bringing in (or removing) water from the subsurface. This is only for mass balance and is not computed from physical characteristics of the surrounding geology.
- A capillary fringe above the water table is calculated using van Genuchten soil parameters.
- Above the capillary fringe, the standard DSSAT upflow is used to move water to upper layers.

### CODE REVIEW

**Comment by chporter** [comment]
After thinking about this more, it may need more testing for various use cases:
- start with no water table, then add a water table.
- start with water table, then remove water table.
- perched water table (I didn't test that this is still working). Use Senthold's data?

**Comment by chporter** [comment]
@fabiooliveira72 This is ready to test and (I think) merge into develop. 
- Initial conditions for water table tested OK
- Water table fluctuations above and below soil profile tested OK
- perched water table behaves as previous version (except that initial conditions are now correctly handled). OK

**Comment by fabiooliveira72** [comment]
Hi @chporter 

That is great. I will add in my notes to test it too. If I find something else, I will report to you here or on Friday.

Thank you!

**Comment by fabiooliveira72** [comment]
Hi @chporter!

I tested your changes and sent you by email with a first analysis just to confirm you have the same outputs

Thank you!

Fabio Oliveira

**Pull request merged**
