### PR TITLE
Adding FlexibleIO to the open source repository

### PR DESCRIPTION
**Pull request by fabiooliveira72**

### CODE REVIEW

**Comment by palderman** [comment]
I was able to compile 0c6889b, but I can't compile with Fabio's changes. I think the CXX flags are not being set properly? See below for compiler error:

Compiler_error

**Comment by fabiooliveira72** [comment]
Hi Dr. Alderman,

Could you please verify if you have C++11 support in your GCC?

I have version 6.3.0 (g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516). This is the stable version from Debian. Versions lower than 6.3.0 may have problems compiling or executing code.

Please let me know if you have another issues.

Thank you

**Comment by palderman** [comment]
Call me "Phil"

My laptop version of gcc is 5.4 so that seems to be the issue.

I was able to compile everything on my office tower with a newer version of gcc (7.4), but it threw an error on the link step that (based on a quick google search) seems to be related to trying to link with the static gfortran libraries:

secure_getenv_err

**Comment by fabiooliveira72** [comment]
Hi Phill,

Please try to install the libgfortran manually.
If you are using Ubuntu you can use this command:

sudo apt-get install libgfortran3

If libfgortran3 is not avaliable try to install the default Ubuntu gfortran lib.

Please, let us know if still have problems.

Thank you

**Comment by palderman** [comment]
I get:
> gfortran is already the newest version (4:7.4.0-1ubuntu2.3)

**Comment by palderman** [comment]
Is there a reason why a static build is necessary? Should we try building with dynamic linking?

**Comment by fabiooliveira72** [comment]
Hi Phill,

I could not reproduce your error in my computer.

We have found some posts on web saying that you should have glibc-static installed in your computer. Take a look at: 
- https://software.intel.com/en-us/articles/error-ld-cannot-find-lm
- https://stackoverflow.com/questions/16024978/usr-bin-ld-cannot-find-lc-while-compiling-with-makefile

Another option: try to remove the static flags from SetFortranFlags.cmake file.

I hope this can help you. Let me know if you need anything else.

Thank you.

**Pull request merged**
