### PR TITLE
Incorporation of the SAMUCA model into DSSAT

### PR DESCRIPTION
**Pull request by Murilodsv**
Hi @GerritHoogenboom, 

Here's the pull request related with the incorporation of the SAMUCA model into DSSAT.

As the new repository do not maintain simulation files anymore into the Data/, here are the files I committed to make available (including field data from my Phd): [Data](https://github.com/DSSAT/dssat-csm-os/files/4241461/Data.zip)

Also, a brief releasing notes: [dssat-samuca-release.pdf](https://github.com/DSSAT/dssat-csm-os/files/4241465/dssat-samuca-release.pdf)

Cheers,
Murilo

### CODE REVIEW

**Comment by chporter** [comment]
Data should be added to a new branch in https://github.com/dssat/dssat-csm-data.

**Comment by chporter** [comment]
Thanks, @Murilodsv . I pulled the code into a new branch on my repo and updated with the latest develop branch here: https://github.com/chporter/dssat-csm-os/tree/samuca
I see a couple of issues right away: 
- console output shows -99 for plant variables. Also, Summary and Evaluate outputs are not linked with the model. Generally, the OPHARV routines which work with console, Overview, and Evaluate outputs. 
- I was actually surprised to see that the descriptive text on headers for daily output files works with GBuild. I thought we had to comment out this kind of text, but it works OK, so this is not an issue as I first thought.

**Comment by Murilodsv** [comment]
Hello @chporter, many thanks for that!

In fact, I was so focused on PlantGro.out and linking the main driving variables and reading coefficients that I missed the Summary and Evaluate outputs. 

- Should I correct that directly from the updated repo (https://github.com/chporter/dssat-csm-os/tree/samuca) or do you prefer that I make a new branch for that?

- I'll create a new samuca's branch from the [dssat-csm-data](https://github.com/dssat/dssat-csm-data) repo and add the data into it asap.

Cheers

**Comment by chporter** [comment]
@Murilodsv , I think you can do the changes in the same branch. My understanding is that the pull request will pull the latest code from that branch. (We can test that theory).

**Pull request merged**
