### PR TITLE
Removed WORK.OUT output; Removed CSCER_CSCRP_CSCAS folder

### PR DESCRIPTION
**Pull request by thiagoferreira53**
Removed WORK.OUT output file from CSCER_Wheat_Barley, CROPSIM, CANEGRO-Sugarcane and CASUPRO-Sugarcane;
Removed CSCER_CSCRP_CSCAS folder;

### CODE REVIEW

**Comment by chporter** [comment]
I'm a little concerned about removing the Canegro output because that model is still maintained at SASRI. 

@matthewjones0001 - @thiagoferreira53 is removing the Work.OUT output files, mostly for CSCER and CSCRP (wheat and barley). But it looks like this also affects CaneGro. The code is still there, but commented out. The rationale is to speed up execution time for large simulations. If you want to keep them, we could instead try to control the quantity of output with the verbose switch or send everything to INFO.OUT which is already controlled by the verbose switch.

**Comment by fabiooliveira72** [comment]
@thiagoferreira53 Please, remove the compiler warnings for Intel Fortran. Check the latest code that Cheryl send in the dssat-csm-os repository and then add your changes in the top for No_Work_Output_branch. It seems you did this before Cheryl merge this warning changes. You need to compile with Intel Fortran and them check the warnings that are coming out from the compiler. Please check them one by one.

Thank you!

**Comment by thiagoferreira53** [comment]
Done!

**Comment by fabiooliveira72** [comment]
@thiagoferreira53 Please update your branch and resolve the conflicts. These conflicts were generated because of water table merge.

**Comment by thiagoferreira53** [comment]
Solved and tested. There were 2 small conflicts related to the WORK.OUT lines I commented and the change from ModuleDefs to ModuleData in the CRP_SeasInit.for.

**Pull request merged**
