### PR TITLE
Updating README.md and build type for DEBUG as default

### PR DESCRIPTION
**Pull request by fabiooliveira72**

### CODE REVIEW

**Comment by fabiooliveira72** [comment]
Hi Dr. Thorp!

I was reviewing and testing your pull request and we just puck back the default build type to DEBUG and updated README file. 

The default PREFIX INSTALLATION for UNIX system was merged previously.

Thank you for you corrections.

Fabio Oliveira

**Comment by kthorp** [comment]
Either way is fine with me.  I'm curious why DEBUG is the preferred way.

**Comment by fabiooliveira72** [comment]
> 

Hi Dr. Thorp!

Thank you for reviewing the code.

The DEBUG is preferred because it can show you the traceback of your subroutine calls when an error happen. So, for developers this is the best choice. Also, we have a lot of people that work with Visual Studio, if we change the default, they will not be able to use the Visual Studio debugger.

The RELEASE is only needed for Cheryl when she does the DSSAT release for the website/Users

Thank you so much,

Fabio Oliveira

**Comment by kthorp** [comment]
That is fine with me.  As another perspective, I am often compiling the code on Linux for use in large numbers of runs.  For that, I set the build type to RELEASE to improve the efficiency of the runs.

**Review by kthorp — APPROVED** [review]

**Pull request merged**
