### PR TITLE
MAXIMA, MINIMA and trait (P/G/N) for ecotype coefficients for CROPGRO crops

### PR DESCRIPTION
**Pull request by thiagoferreira53**

### CODE REVIEW

**Comment by thiagoferreira53** [comment]
@chporter @fabiooliveira72 

Nothing related to this commit but I noticed when I was running CropTest that the CO2EM values in SUMMARY.OUT are reaching negative values. Is that correct?

**Comment by fabiooliveira72** [comment]
Hi @thiagoferreira53

Thanks for letting us know. I will check if something is happening.

Fabio Oliveira

**Comment by chporter** [comment]
Hi, @thiagoferreira53 . The method of calculating net CO2 emissions from a field have been changed to match IPCC methods so that DSSAT outputs are consistent with other sources of CO2 emissions in the GHG literature. With these new calculations, net CO2 emissions can be negative, indicating an uptake of C to the soil (sequestration).

**Comment by chporter** [comment]
However, this presents a problem in reporting because a value of "-99" could be a valid value for this variable. We need to think about how best to handle this. I was thinking that an integer value of "-99" could be output if the value is missing and a real value of "-99.0" if it's an actual calculated value.

**Pull request closed without merging**
