### PR TITLE
Provide a build environment using a nix-shell.

### PR DESCRIPTION
**Pull request by philderbeast**

### CODE REVIEW

**Review by frostbytten — COMMENTED** [review]
We might want to subhead these with `Using Nix Shell` and `Using CMake natively` so people don't get confused with the build path. The Nix shell itself is fine.

**Comment by philderbeast** [comment]
@frostbytten I've added subsections, toolchain and build steps.

**Comment by chporter** [comment]
@fabiooliveira72 , can you take a look at this and test for our "normal" user? Thanks!

**Comment by fabiooliveira72** [comment]
@chporter and @frostbytten Yes, for sure. I am going to finish a task here for the DSSAT Sprint and then I will test this code. Thank you.

**Comment by chporter** [comment]
Closing - we should create a script for working with Nix shell. Fabio to report back on the best way to handle this.

**Pull request closed without merging**
